//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKnjiznica.Commons {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKnjiznica.Common.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate privilegije za pristup aplikaciji..
        /// </summary>
        public static string ACCOUNT_HAS_NO_PRIVILEGES_TO_ACCESS_APP {
            get {
                return ResourceManager.GetString("ACCOUNT_HAS_NO_PRIVILEGES_TO_ACCESS_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun je deaktiviran.
        /// </summary>
        public static string ACCOUNT_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto.
        /// </summary>
        public static string ACCOUNT_WITH_USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("ACCOUNT_WITH_USERNAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcija uspješna.
        /// </summary>
        public static string ACTION_SUCCESS {
            get {
                return ResourceManager.GetString("ACTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kako bi ste završili transakciju potrebno je dodati najmanje jednu knjigu u košaricu..
        /// </summary>
        public static string AT_LEAST_ONE_BOOK_REQUIRED {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_BOOK_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knjiga je kupljena..
        /// </summary>
        public static string BOOK_ALREADY_BUYED {
            get {
                return ResourceManager.GetString("BOOK_ALREADY_BUYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čestitamo, transakcija je uspješno prošla. Knjige su dostupne na Vašem mailu..
        /// </summary>
        public static string BOOK_BUY_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("BOOK_BUY_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcija uspješna.
        /// </summary>
        public static string BOOK_BUY_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("BOOK_BUY_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knjiga je u košarici.
        /// </summary>
        public static string BOOK_IN_BASKET {
            get {
                return ResourceManager.GetString("BOOK_IN_BASKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knjiga je poslana na mail..
        /// </summary>
        public static string BOOK_RESEND_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("BOOK_RESEND_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno.
        /// </summary>
        public static string BOOK_RESEND_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("BOOK_RESEND_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija ne postoji.
        /// </summary>
        public static string CATEGORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija s tim imenom već postoji..
        /// </summary>
        public static string CATEGORY_WITH_THAT_NAME_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_WITH_THAT_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija je uspješna.
        /// </summary>
        public static string CLIENT_ADD_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("CLIENT_ADD_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno.
        /// </summary>
        public static string CLIENT_ADD_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("CLIENT_ADD_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravan novčani iznos.
        /// </summary>
        public static string ENTER_VALID_AMOUNT {
            get {
                return ResourceManager.GetString("ENTER_VALID_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravan naziv kategorije.
        /// </summary>
        public static string ENTER_VALID_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("ENTER_VALID_CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upišite ispravno ime za autora.
        /// </summary>
        public static string ERR_AUTHOR_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_AUTHOR_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upišite ispravno ime za knjigu.
        /// </summary>
        public static string ERR_BOOK_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_BOOK_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijentski račun nije aktivan.
        /// </summary>
        public static string ERR_CLIENT_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_CLIENT_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum od mora biti prije datuma do.
        /// </summary>
        public static string ERR_DATE_FROM_MUST_BE_BEFORE_DATE_TO {
            get {
                return ResourceManager.GetString("ERR_DATE_FROM_MUST_BE_BEFORE_DATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum do mora biti poslije datuma od.
        /// </summary>
        public static string ERR_DATE_TO_MUST_BE_AFTER_DATE_FROM {
            get {
                return ResourceManager.GetString("ERR_DATE_TO_MUST_BE_AFTER_DATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom preuzimanja.
        /// </summary>
        public static string ERR_DOWNLOADING_BOOK_FILE {
            get {
                return ResourceManager.GetString("ERR_DOWNLOADING_BOOK_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upišite ispravnu cijenu.
        /// </summary>
        public static string ERR_ENTER_VALID_PRICE {
            get {
                return ResourceManager.GetString("ERR_ENTER_VALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pravilan email.
        /// </summary>
        public static string ERR_FIELD_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka se mora sastojati od najmanje 6 karaktera uključujući mala, velika slova i brojeve..
        /// </summary>
        public static string ERR_FIELD_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj telefona u ispravnom formatu(npr +3876xxxxxx, 06xxxxxxx).
        /// </summary>
        public static string ERR_FIELD_PHONE_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora biti duže od 5 karaktera.
        /// </summary>
        public static string ERR_FIELD_USERNAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_USERNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime su obavezna polja.
        /// </summary>
        public static string ERR_FIRST_AND_LAST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_FIRST_AND_LAST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje..
        /// </summary>
        public static string ERR_FIRST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_FIRST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova i stara lozinka se mora sastojati od najmanje 6 karaktera uključujući mala, velika slova i brojeve..
        /// </summary>
        public static string ERR_INVALID_PASSWORD_FIELDS {
            get {
                return ResourceManager.GetString("ERR_INVALID_PASSWORD_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje..
        /// </summary>
        public static string ERR_LAST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_LAST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jednu knjigu.
        /// </summary>
        public static string ERR_SELECT_ONE_BOOK {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite barem jednu kategoriju.
        /// </summary>
        public static string ERR_SELECT_ONE_CATEGORY {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite knjigu.
        /// </summary>
        public static string ERR_UPLOAD_BOOK {
            get {
                return ResourceManager.GetString("ERR_UPLOAD_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite sliku.
        /// </summary>
        public static string ERR_UPLOAD_PICTURE {
            get {
                return ResourceManager.GetString("ERR_UPLOAD_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string LABEL_ADD {
            get {
                return ResourceManager.GetString("LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni.
        /// </summary>
        public static string LABEL_UPDATE {
            get {
                return ResourceManager.GetString("LABEL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string LBL_OK {
            get {
                return ResourceManager.GetString("LBL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom logiranja.
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate dovoljno novca na računu..
        /// </summary>
        public static string NOT_ENOUGH_MONEY_ON_ACCOUNT {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_MONEY_ON_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena lozinke nije uspjela.
        /// </summary>
        public static string PASSWORD_CHANGE_FAILED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo popunite polja.
        /// </summary>
        public static string PLEASE_FILL_IN_FIELDS {
            get {
                return ResourceManager.GetString("PLEASE_FILL_IN_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite korisnika.
        /// </summary>
        public static string PLEASE_SELECT_USER {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil je uspješno izmjenjen..
        /// </summary>
        public static string PROFILE_UPDATE_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("PROFILE_UPDATE_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom registracije.
        /// </summary>
        public static string REGISTRATION_ERROR {
            get {
                return ResourceManager.GetString("REGISTRATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupovina.
        /// </summary>
        public static string TRANSACTION_TYPE_BUY {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplata.
        /// </summary>
        public static string TRANSACTION_TYPE_PAY_IN {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_PAY_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do neočekivane greške..
        /// </summary>
        public static string UNEXPECTED_ERROR_OCURRED {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristupni podaci nisu ispravni.
        /// </summary>
        public static string USERNAME_OR_PASSWORD_INCORRENT {
            get {
                return ResourceManager.GetString("USERNAME_OR_PASSWORD_INCORRENT", resourceCulture);
            }
        }
    }
}
