//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKnjiznica.Commons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKnjiznica.Commons.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički račun je deaktiviran.
        /// </summary>
        public static string ACCOUNT_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto.
        /// </summary>
        public static string ACCOUNT_WITH_USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("ACCOUNT_WITH_USERNAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija ne postoji.
        /// </summary>
        public static string CATEGORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija s tim imenom već postoji..
        /// </summary>
        public static string CATEGORY_WITH_THAT_NAME_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_WITH_THAT_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravan naziv kategorije.
        /// </summary>
        public static string ENTER_VALID_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("ENTER_VALID_CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pravilan email.
        /// </summary>
        public static string ERR_FIELD_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka se mora sastojati od najmanje 6 karaktera uključujući mala, velika slova i brojeve..
        /// </summary>
        public static string ERR_FIELD_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravan broj telefona.
        /// </summary>
        public static string ERR_FIELD_PHONE_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora biti duže od 5 karaktera.
        /// </summary>
        public static string ERR_FIELD_USERNAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_FIELD_USERNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje..
        /// </summary>
        public static string ERR_FIRST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_FIRST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje..
        /// </summary>
        public static string ERR_LAST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_LAST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite korisnika.
        /// </summary>
        public static string PLEASE_SELECT_USER {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do neočekivane greške..
        /// </summary>
        public static string UNEXPECTED_ERROR_OCURRED {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristupni podaci nisu ispravni.
        /// </summary>
        public static string USERNAME_OR_PASSWORD_INCORRENT {
            get {
                return ResourceManager.GetString("USERNAME_OR_PASSWORD_INCORRENT", resourceCulture);
            }
        }
    }
}
