// <auto-generated />
namespace eKnjiznica.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BuyedBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuyedBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201806120745178_BuyedBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
